name: appinio_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.3.0
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
